#!/usr/bin/env python3
"""Object-by-object: does the deliverable still say what the source said?

The property-distribution gate compares how much of each formatting class
survives. It cannot see a figure that moved two paragraphs, a sentence that
vanished, or two questions that swapped places — every one of those keeps the
distributions intact, and every one of them was found by a person reading the
page instead.

This compares the two documents as sequences of objects:

* 文本完整性 — every source paragraph's text is either in the output or on the
  exclusion list with a reason
* 文本顺序   — the source locators appear in the output in the order the source
  has them, per document
* 图片归属   — every source picture is in the output, in the same paragraph,
  at the same position among that paragraph's text
* 图片尺寸   — the printed width follows the declared rule (source width scaled
  by our body size over the paragraph's own size), not some default

Normalisation is the whole difficulty. The output legitimately differs from the
source: markers are regenerated by Word, formulas drawn as pictures became
text, reaction arrows became equations, repeated 专题/课题 titles are printed
once. Each of those is declared in the blueprint, so the comparison subtracts
what was declared and reports only what was not.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import re
import unicodedata
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

MARKER = re.compile(r"^\s*(?:\d{1,2}\s*[．.]|[A-H]\s*[．.]|[（(]\s*\d{1,2}\s*[)）]|[①-⑳])\s*")
# 只差这些的,不是差异,是本规范说过要这么做的事。留在报告里会把它训练成
# 「反正总是有一堆」,于是真出问题时也没人看。理由随判定一起写出来。
DECLARED = (
    ("MARKER_REGENERATED", "标号由 Word 生成,源里的字面标号不再印",
     lambda diff: bool(diff) and bool(re.fullmatch(r"[①-⑳\dA-H．.、（）()\s]+", diff))),
    ("TRANSCRIBED_ADDED", "公式图已转写为文字,成品比源多出这些字",
     lambda diff: False),
)
SENTINELS = "".join(chr(c) for c in range(0xE000, 0xE010))
ARROW_GLYPHS = re.compile(r"[—–─\-→⟶\s]+")


def drop_arrow_glyphs(text: str) -> str:
    """The sentence with every character that draws an arrow taken out.

    The equations the source typed as 「镁+氧气——点燃→氧化镁」 now print as
    Word's own equation, so the arrow lives inside the maths and no longer
    appears in the text run. Comparing the two raw reads as 17 changed
    paragraphs. Taking the arrow out of both sides and requiring what remains
    to match character for character proves the arrow was the only thing that
    moved — which a blanket exemption would not.
    """
    return ARROW_GLYPHS.sub("", text)


def load_engine(path: Path):
    spec = importlib.util.spec_from_file_location("carve_engine", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def paragraph_of(locator: str) -> str:
    """The paragraph a locator belongs to, whichever child it names.

    A figure is provenanced against itself — 「body/p[38]/drawing[1]/rId9」 —
    and an option against its label — 「body/p[39]」 with objectPart A. Comparing
    those raw against the source's paragraph locators matched nothing and read
    as 250 lost figures.
    """
    value = locator.split(":", 1)[-1].split("#", 1)[0]
    for child in ("/drawing", "/shape", "/pict", "/alternateContent", "/object"):
        value = value.split(child)[0]
    return value


def normalise(text: str) -> str:
    """What two renderings of the same sentence have in common.

    Width, whitespace and the regenerated marker are ours to change; the words
    are not. Sentinels are stripped because they are carve-internal.
    """
    text = unicodedata.normalize("NFKC", text or "")
    for mark in SENTINELS:
        text = text.replace(mark, "")
    text = MARKER.sub("", text)
    return re.sub(r"[\s　]+", "", text)


def normalised_title(text: str, mapping: dict) -> str:
    """The title as the spec writes it, so a declared rename is not a defect."""
    for family in ("titleNormalization", "calloutTitleNormalization"):
        for rule in (mapping.get(family) or {}).get("patterns") or []:
            fixed, count = re.subn(rule["match"], rule["replace"], text, count=1)
            if count:
                return fixed.strip()
    return text


def source_side(engine, schema, registry: dict) -> dict[str, dict[str, Any]]:
    """Each source document, read the same way the carve reads it."""
    found: dict[str, dict[str, Any]] = {}
    for document in registry["documents"]:
        if document["role"] != "original_word":
            continue
        diagnostics = engine.Diagnostics(schema.diagnostics)
        blocks = engine.read_blocks(document["physicalPath"], schema, diagnostics)
        order: dict[str, int] = {}
        text: dict[str, str] = {}
        figures: list[dict[str, Any]] = []
        for position, block in enumerate(blocks):
            locator = block["locator"]
            order[locator] = position
            # A table block's own text is already the whole table's text;
            # adding the cells again counted every table twice and made the
            # output look like half of it had gone.
            body = block.get("text") or ""
            for item in block.get("textboxParagraphs") or []:
                body += item.get("text") or ""
            text[locator] = body
            for index, ref in enumerate(block.get("imageRefs") or [], start=1):
                if ref.get("kind") in ("transcribed",) or not ref.get("hash"):
                    continue
                figures.append({
                    "locator": locator, "ordinal": index,
                    "hash": ref["hash"], "offset": ref.get("offset"),
                    "widthEmu": ref.get("widthEmu"),
                    "paragraphSizePt": block.get("sourceSizePt"),
                    "position": position})
        found[document["physicalPath"]] = {
            "lesson": document["lesson"], "period": document.get("period"),
            "order": order, "text": text, "figures": figures,
            "blocks": len(blocks)}
    return found


def object_paragraphs(manifest: Path | None) -> dict[str, str]:
    """objectId → the paragraph the object sits in.

    A standalone figure block is provenanced by object id rather than by path,
    because the object is the thing being placed. The comparison needs the
    paragraph, and only the manifest knows both.
    """
    if manifest is None or not manifest.is_file():
        return {}
    data = json.loads(manifest.read_text(encoding="utf-8"))
    found: dict[str, str] = {}
    for document in data.get("sourceDocuments") or []:
        for item in document.get("objects") or []:
            identifier = item.get("objectId")
            value = (item.get("locator") or {}).get("value")
            if identifier and value:
                found[identifier] = paragraph_of(str(value))
    return found


def output_side(blueprint: dict, paragraphs: dict[str, str]) -> dict[str, dict[str, Any]]:
    """The blueprint, indexed the same way: by source document and locator."""
    by_hash = {d["sha256"]: d["path"] for d in blueprint["sourceDocuments"]}
    found: dict[str, dict[str, Any]] = defaultdict(
        lambda: {"text": defaultdict(str), "sequence": [], "figures": []})
    for index, block in enumerate(blueprint["blocks"]):
        source = block.get("source") or {}
        digest = source.get("sha256")
        if not digest or digest not in by_hash:
            continue
        raw = str((source.get("locator") or {}).get("value") or "")
        locator = paragraphs.get(raw) or paragraph_of(raw)
        page = found[by_hash[digest]]
        segments = list(block.get("segments") or [])
        for row in block.get("rows") or []:
            for cell in row:
                segments.extend(cell.get("segments") or [])
        body = "".join(
            (s.get("text") or "") if s.get("kind") != "reaction_arrow"
            else (str(s.get("over") or "") + str(s.get("under") or ""))
            for s in segments)
        page["text"][locator] += body
        # A row of options laid out per question carries options the source
        # typed on the next paragraph down. Those source paragraphs are named
        # in additionalSources, and their words are in this block — comparing
        # each source paragraph only against the block that happens to anchor
        # it read as 33 half-missing option rows.
        for extra in block.get("additionalSources") or []:
            raw_extra = str((extra.get("locator") or {}).get("value") or "")
            page["text"][paragraphs.get(raw_extra) or paragraph_of(raw_extra)] += body
        page["sequence"].append((index, locator))
        for order, segment in enumerate(segments, start=1):
            if segment.get("kind") != "inline_image":
                continue
            page["figures"].append({
                "locator": locator, "blockIndex": index,
                "path": segment.get("path"),
                "widthMm": segment.get("width_mm"),
                "before": "".join(s.get("text") or ""
                                  for s in segments[:order - 1])[-12:]})
        for extra in block.get("additionalSources") or []:
            raw_extra = str((extra.get("locator") or {}).get("value") or "")
            where = paragraphs.get(raw_extra) or paragraph_of(raw_extra)
            for order, segment in enumerate(segments, start=1):
                if segment.get("kind") != "inline_image":
                    continue
                page["figures"].append({
                    "locator": where, "blockIndex": index,
                    "path": segment.get("path"),
                    "widthMm": segment.get("width_mm"),
                    "before": "".join(s.get("text") or ""
                                      for s in segments[:order - 1])[-12:]})
        if block.get("type") == "image":
            page["figures"].append({
                "locator": locator, "blockIndex": index,
                "path": block.get("path"), "widthMm": block.get("width_mm"),
                "before": ""})
    return found


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--engine", required=True, type=Path)
    parser.add_argument("--schema", required=True, type=Path)
    parser.add_argument("--registry", required=True, type=Path)
    parser.add_argument("--blueprint", required=True, type=Path)
    parser.add_argument("--mapping", type=Path)
    parser.add_argument("--object-manifest", type=Path,
                        help="objectId 与段落的对照,独立图片块只按 objectId 记来源")
    parser.add_argument("--report", required=True, type=Path)
    args = parser.parse_args()

    engine = load_engine(args.engine)
    schema = engine.Schema(json.loads(args.schema.read_text(encoding="utf-8")))
    registry = json.loads(args.registry.read_text(encoding="utf-8"))
    blueprint = json.loads(args.blueprint.read_text(encoding="utf-8"))
    mapping = json.loads(args.mapping.read_text(encoding="utf-8")) if args.mapping else {}
    body_pt = float((mapping.get("typography") or {}).get("bodySizePt") or 12)

    paragraphs = object_paragraphs(args.object_manifest)

    # An exclusion names the object it excludes, so a figure is listed by its
    # own locator — 「body/p[1]/drawing[1]/rId5」 — not by the paragraph holding
    # it. Comparing paragraph locators against those matched nothing and called
    # 403 declared decorations lost.
    def owner(record: dict) -> tuple[str, str, bool]:
        source = record.get("source") or {}
        value = str((source.get("locator") or {}).get("value") or "").split(":", 1)[-1]
        kind = str((source.get("locator") or {}).get("kind") or "")
        return (source.get("sha256"), paragraphs.get(value) or paragraph_of(value),
                kind in ("image", "shape"))

    excluded: set[tuple[str, str]] = set()
    excluded_figures: Counter = Counter()
    carried: set[tuple[str, str]] = set()
    for record in blueprint.get("sourceObjectExclusions") or []:
        digest, where, is_figure = owner(record)
        (excluded_figures.update([(digest, where)]) if is_figure
         else excluded.add((digest, where)))
    for record in blueprint.get("sourceObjectReviewQueue") or []:
        digest, where, is_figure = owner(record)
        (excluded_figures.update([(digest, where)]) if is_figure
         else carried.add((digest, where)))
    # A bitmap the spec replaced with a Word chart. Read off the blueprint's
    # own chart blocks, not off a list of exemptions: the figure is only
    # excused where a chart block actually stands in its place and names it.
    charted_figures: Counter = Counter()
    for block in blueprint["blocks"]:
        # Keyed on 「this block names the bitmap it stands in for」, not on a
        # list of block types. The type list had to be edited every time a new
        # kind of substitution appeared — a chart, then a drawing, then a
        # paragraph and a table — and a substitution the list had not caught up
        # with reported as a lost figure.
        if not block.get("substitutedSourceImage"):
            continue
        # Resolved the same way owner() resolves an exclusion: a figure block
        # is provenanced by object id, and only the manifest knows which
        # paragraph that object sits in.
        digest, where, _ = owner(block)
        charted_figures.update([(digest, where)])
    digest_of = {d["path"]: d["sha256"] for d in blueprint["sourceDocuments"]}

    source = source_side(engine, schema, registry)
    output = output_side(blueprint, paragraphs)

    findings: list[dict[str, Any]] = []
    counts: Counter = Counter()

    for path, page in source.items():
        produced = output.get(path)
        if produced is None:
            findings.append({"code": "DOCUMENT_MISSING", "document": path})
            continue
        digest = digest_of.get(path)

        # 1. 文本完整性
        for locator, text in page["text"].items():
            wanted = normalise(text)
            if not wanted:
                continue
            got = normalise(produced["text"].get(locator, ""))
            counts["段落"] += 1
            if got == wanted:
                continue
            if (digest, locator) in excluded or (digest, locator) in carried:
                counts["已声明排除或承载"] += 1
                continue
            if wanted in got or got in wanted:
                counts["部分一致"] += 1
                longer, shorter = (got, wanted) if len(got) > len(wanted) else (wanted, got)
                at = longer.find(shorter)
                extra = longer[:at] + longer[at + len(shorter):]
                if len(got) > len(wanted):
                    counts["转写补入的文字"] += 1
                    continue
                declared = next((why for _, why, matches in DECLARED
                                 if matches(extra)), None)
                if declared:
                    counts["标号由 Word 重排"] += 1
                    continue
                findings.append({
                    "code": "TEXT_PARTIAL", "document": page["lesson"],
                    "locator": locator, "side": "成品缺少",
                    "diff": (longer[:at] + "‖" + longer[at + len(shorter):])[:60]})
                continue
            # 成品里一个字不少、只是多了转写出来的字,同样是声明过的事
            if all(letter in got for letter in wanted):
                counts["转写补入的文字"] += 1
                continue
            if normalise(normalised_title(text, mapping)) == got:
                counts["标题按规范改写"] += 1
                continue
            # Counted apart from the line above, and deliberately. That one is
            # the same layout rule applied to every title; this is one title
            # whose wording we changed. Folding them together would let 「the
            # source says this」 quietly stop being true for a heading while the
            # report still read as if only spacing had moved.
            if any(text.strip() == entry["from"]
                   and normalise(str(entry["to"])) == got
                   for entry in (mapping.get("titleOverrides") or {}).get("entries") or []):
                counts["标题按一次性裁决改写(措辞是我们的)"] += 1
                continue
            # 源里手打的「——点燃→」已按裁决改成 Word 原生公式,箭头进了公式、
            # 不再是正文字符。这不是放行一整类差异:两边都把画箭头的字符抹掉后
            # 必须逐字相同,否则仍然报。抹掉箭头还对不上的,是真差异。
            if drop_arrow_glyphs(wanted) == drop_arrow_glyphs(got) \
                    and wanted != got:
                counts["反应箭头已转为公式"] += 1
                continue
            findings.append({
                "code": "TEXT_MISSING" if not got else "TEXT_CHANGED",
                "document": page["lesson"], "locator": locator,
                "source": text[:70], "output": produced["text"].get(locator, "")[:70]})

        # 2. 文本顺序
        seen: list[int] = []
        for _, locator in sorted(produced["sequence"]):
            position = page["order"].get(locator)
            if position is not None:
                seen.append(position)
        inversions = sum(1 for a, b in zip(seen, seen[1:]) if b < a)
        counts["顺序检查"] += 1
        if inversions:
            findings.append({"code": "ORDER_INVERTED", "document": page["lesson"],
                             "inversions": inversions, "blocks": len(seen)})

        # 3+4. 图片归属与尺寸
        produced_by_locator: dict[str, list[dict[str, Any]]] = defaultdict(list)
        for figure in produced["figures"]:
            produced_by_locator[figure["locator"]].append(figure)
        wanted_here: Counter = Counter(f["locator"] for f in page["figures"])
        for locator, wanted in wanted_here.items():
            counts["图片"] += wanted
            got = len(produced_by_locator.get(locator) or [])
            declared = excluded_figures.get((digest, locator), 0)
            # A figure the spec turned into a Word chart is not a lost figure.
            # 「声明过就放行」 would be too weak: the substitution is only
            # accepted when the blueprint really does carry a chart block whose
            # substitutedSourceImage names this very bitmap.
            declared += charted_figures.get((digest, locator), 0)
            counts["图片已声明排除"] += min(declared, wanted)
            if got + declared < wanted:
                findings.append({
                    "code": "FIGURE_LOST", "document": page["lesson"],
                    "locator": locator, "source": wanted,
                    "output": got, "declared": declared})
        for figure in page["figures"]:
            here = produced_by_locator.get(figure["locator"]) or []
            # A WMF cannot be placed, so it travels as its registered raster
            # rendition — 「<hash>.render.png」 — while the WMF stays its source
            # identity. Comparing file stems against the hash called those a
            # different picture.
            def is_same(found: dict) -> bool:
                stem = Path(str(found.get("path") or "")).stem
                return stem in (figure["hash"], figure["hash"] + ".render")

            match = next((f for f in here if is_same(f)), None)
            if match is None:
                if (not excluded_figures.get((digest, figure["locator"]))
                        and not charted_figures.get(
                            (digest, paragraph_of(figure["locator"])))):
                    findings.append({
                        "code": "FIGURE_DIFFERENT_ASSET",
                        "document": page["lesson"], "locator": figure["locator"],
                        "hash": figure["hash"],
                        "found": [Path(str(f.get("path") or "")).stem for f in here]})
                continue
            wanted_mm = None
            if figure.get("widthEmu") and figure.get("paragraphSizePt"):
                ratio = body_pt / float(figure["paragraphSizePt"])
                wanted_mm = round(int(figure["widthEmu"]) / 36000 * ratio, 2)
            if wanted_mm and match.get("widthMm"):
                drift = abs(float(match["widthMm"]) - wanted_mm)
                if drift > 0.05:
                    findings.append({
                        "code": "FIGURE_WIDTH_DRIFT",
                        "document": page["lesson"], "locator": figure["locator"],
                        "wantedMm": wanted_mm, "gotMm": match["widthMm"]})
            elif not match.get("widthMm"):
                findings.append({
                    "code": "FIGURE_WIDTH_MISSING",
                    "document": page["lesson"], "locator": figure["locator"]})

    report = {
        "schemaVersion": "chengziclass.source-output-object-verification.v1",
        "blueprint": str(args.blueprint),
        "documents": len(source),
        "checked": dict(counts),
        "findingCounts": dict(Counter(f["code"] for f in findings)),
        "findings": findings,
    }
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, ensure_ascii=False, indent=1),
                           encoding="utf-8")
    print(json.dumps({"checked": report["checked"],
                      "findings": report["findingCounts"]},
                     ensure_ascii=False, indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
